{% set name = "ctgan" %}
{% set version = "0.10.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ctgan-{{ version }}.tar.gz
  sha256: dac9d5edf7bb64c3ce156c4ed6089c1cec8dc36463710b9fc71968b286dbe600

build:
  number: 0
  noarch: python
  entry_points:
    - ctgan=ctgan.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.8,<3.13
  run:
    - numpy >=1.20.0,<2
    - pandas >=1.1.3
    - python >=3.8,<3.13
    - pytorch >=1.8
    - rdt >=1.11.0
    - tqdm >=4.29,<5

test:
  imports:
    - ctgan
    - ctgan.synthesizers
  commands:
    - ctgan --help
  requires:
    - pip
    - pytest

about:
  home: https://github.com/sdv-dev/CTGAN
  summary: Conditional GAN for Tabular Data
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sdv
