{% set name = "ctgan" %}
{% set version = "0.9.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ctgan-{{ version }}.tar.gz
  sha256: cf680f16a59df57f977f010f07372313f867e7c9e7bebff59a124bd919162cd7

build:
  number: 0
  noarch: python
  entry_points:
    - ctgan=ctgan.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.8,<3.12
  run:
    - numpy >=1.20.0,<2
    - pandas >=1.1.3
    - python >=3.8,<3.12
    - pytorch >=1.8
    - rdt >=1.3.0,<2
    - scikit-learn >=1.1.3,<2
    - tqdm >=4.15,<5

test:
  imports:
    - ctgan
    - ctgan.synthesizers
  commands:
    - ctgan --help
    - pytest
  requires:
    - pip
    - pytest
  source_files:
    - tests

about:
  home: https://github.com/sdv-dev/CTGAN
  summary: Conditional GAN for Tabular Data
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sdv
