{% set name = "ctgan" %}
{% set version = "0.7.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ctgan-{{ version }}.tar.gz
  sha256: a32a86bda8cb5b4df41558f64ad5c7623399428ab41e90609a66b90052ccf717

build:
  number: 0
  noarch: python
  entry_points:
    - ctgan=ctgan.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.7,<3.11
  run:
    - numpy >=1.20.0,<2
    - packaging >=20,<22
    - pandas >=1.1.3,<2
    - python >=3.7,<3.11
    - rdt >=1.3.0,<2
    - scikit-learn >=1.1.3,<2
    - pytorch >=1.4,<2
    - torchvision >=0.5.0,<1

test:
  imports:
    - ctgan
    - ctgan.synthesizers
  commands:
    - ctgan --help
    - pytest
  requires:
    - pip
    - pytest
  source_files:
    - tests

about:
  home: https://github.com/sdv-dev/CTGAN
  summary: Conditional GAN for Tabular Data
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sdv
