{% set name = "ctgan" %}
{% set version = "0.5.0" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ctgan-{{ version }}.tar.gz
  sha256: b8a5dbf21dab2d2e2690013f13feb0922f5bad13440b15bc031ce9d58c7fb988

build:
  number: 0
  noarch: python
  entry_points:
    - ctgan=ctgan.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.6,<3.9
  run:
    - numpy >=1.18.0,<2
    - packaging
    - pandas >=1.1,<1.1.5
    - python >=3.6,<3.9
    - rdt >=0.5.0,<0.6
    - scikit-learn >=0.23,<1
    - pytorch >=1.4,<2
    - torchvision >=0.5.0,<1

test:
  imports:
    - ctgan
    - ctgan.synthesizers
  commands:
    - pip check
    - ctgan --help
  requires:
    - pip

about:
  home: https://github.com/sdv-dev/CTGAN
  summary: Conditional GAN for Tabular Data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rdt
