{% set name = "ctgan" %}
{% set version = "0.10.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ctgan-{{ version }}.tar.gz
  sha256: e696fcb52c1591e589498eb42ff3d465bfd9052dadb75ee0eef85993ee0d358e

build:
  number: 1
  noarch: python
  entry_points:
    - ctgan=ctgan.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python {{ python_min }}
  run:
    - numpy >=1.21.0,<2
    - pandas >=1.4.0
    - python >={{ python_min }},<3.13
    - pytorch >=1.9
    - rdt >=1.11.0
    - tqdm >=4.29,<5

test:
  imports:
    - ctgan
    - ctgan.synthesizers
  commands:
    - ctgan --help
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/sdv-dev/CTGAN
  summary: Conditional GAN for Tabular Data
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sdv
