{% set name = "ctgan" %}
{% set version = "0.11.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/ctgan-{{ version }}.tar.gz
  sha256: d6a5dee0f063db4d44d188865fb52ae4cc95c9ed42c679c4e9fcab39163f850e

build:
  number: 0
  noarch: python
  entry_points:
    - ctgan=ctgan.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python {{ python_min }}
  run:
    - numpy >=1.21.0,<2
    - pandas >=1.4.0
    - python >={{ python_min }},<3.14
    - pytorch >=1.13.0
    - rdt >=1.14.0
    - tqdm >=4.29,<5

test:
  imports:
    - ctgan
    - ctgan.synthesizers
  commands:
    - ctgan --help
  requires:
    - pip
    - pytest
    - python {{ python_min }}

about:
  home: https://github.com/sdv-dev/CTGAN
  summary: Conditional GAN for Tabular Data
  license: BUSL-1.1
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/sdv
