{% set name = "ctgan" %}
{% set version = "0.5.1" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/ctgan-{{ version }}.tar.gz
  sha256: 21e1ebfe6aed6dc4f9edae64f6f59a9d3825401a0ae6dd9b8514a0fbc7752340

build:
  number: 0
  noarch: python
  entry_points:
    - ctgan=ctgan.__main__:main
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - pip
    - pytest-runner >=2.11.1
    - python >=3.6,<3.10
  run:
    - numpy >=1.18.0,<2
    - packaging >=20,<22
    - pandas >=1.1.3,<2
    - python >=3.6,<3.10
    - rdt >=0.6.1,<0.7
    - scikit-learn >=0.24,<2
    - pytorch >=1.4,<2
    - torchvision >=0.5.0,<1

test:
  imports:
    - ctgan
    - ctgan.synthesizers
  commands:
    - ctgan --help
    - pytest
  requires:
    - pip
    - pytest
  source_files:
    - tests

about:
  home: https://github.com/sdv-dev/CTGAN
  summary: Conditional GAN for Tabular Data
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - conda-forge/rdt
